global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "hypesoft-api"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "api:5000"

  - job_name: "hypesoft-frontend"
    metrics_path: /api/metrics
    static_configs:
      - targets:
          - "frontend:3000"
