global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "hypesoft-api"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "host.docker.internal:5000"
          - "host.docker.internal:5234"
