apiVersion: 1

contactPoints:
  - orgId: 1
    name: email-notification
    receivers:
      - uid: email-receiver
        type: email
        settings:
          addresses: heringer.ulrich@gmail.com
          singleEmail: true
        disableResolveMessage: false
