apiVersion: 1

policies:
  - orgId: 1
    receiver: email-notification
    group_by:
      - grafana_folder
      - alertname
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    routes:
      - receiver: email-notification
        object_matchers:
          - ["severity", "=", "critical"]
        continue: false
